### ISSUE TITLE
Infos à ajouter

### ISSUE THREAD

**Issue by Ealhad** [hverlin/site_integration#3]
Pour chaque événement, devraient apparaître : 
 - le matos à prévoir (genre les tickets de tram)
 - le coût potentiel de la chose

**Comment by Ealhad** [comment]
Même que il paraît qu'il faudrait mettre des photos en plus.

**Comment by hverlin** [comment]
pour les infos c'est ok :)

**Comment by Ealhad** [comment]
Je mets en ligne !

**Comment by hverlin** [comment]
je crois que les cartes gmap sont pas toutes ok

**Comment by Ealhad** [comment]
C'est réglé, y avait des guillemets foireux.
