### ISSUE TITLE
Mise à jour : comment qu'on fait ?

### ISSUE THREAD

**Issue by Ealhad** [hverlin/site_integration#4]
Il va falloir changer tout le contenu, en particulier les noms et les **photos**.

Comment s'organise-t-on pour récupérer tout ce bazar ? Un drive, une dropbox, une autre alternative ?

---

La question de la collaboration reste ouverte. Si on ouvre le projet à plus de gens, comment on gère ça ?

**Comment by LoicTouzard** [comment]
Tu parles bien de ce repo ? Tu veux ouvrir le site intégration à plus de monde ?
Pour la mise en prod cela dépend de quelle manière tu as accès au serveur ( ssh, ftp, autre ?).
On peut créer un branche `prod` qui correspondrait en permanence à l'état du serveur : avant une mise en prod, on fait une fusion dans la branche `prod` de la branche  `master`, on peut même rajouter une realease si ça vous amuse :stuck_out_tongue: . Puis on met à jour le serv avec le contenu de la branche `prod`.
Je pense pas qu'on ai besoin d'outils d'intégration continue / automatique pour ce genre de projet de petite taille.

**Comment by Ealhad** [comment]
Ah, flûte. Je me suis planté de projet :D
